PUT http://localhost:8080/beta/u?id=5
Content-Type: application/json

{  "name" : "Alex",
  "id": 9,
  "tool": {"first": "ide","second": "database"},
  "creamlist" : [{"value":  "R"},{"value": "DDDD"}]

}